### Support Vector Machine vs Random Forest

In [1]:
from sklearn import svm
import pandas as pd
import numpy as np

In [2]:
#data random
x_train = np.random.random((3000,2))
y_train = np.zeros((3000))

x_test = np.random.random((300,2))
y_test = np.zeros((300))

In [3]:
x_train = np.around(x_train, decimals=2)
x_test = np.around(x_test, decimals=2)

In [4]:
x_train[0]

array([0.72, 0.66])

In [5]:
a=0
for x in x_train:
  #get first digit after point.
  # [0.52, 0.36] p->5, q->3
  # y_train 0(! (case 1 or 2) ) ,1(both odd) or 2(both even)  
  p = np.trunc(x[0]*10) 
  q = np.trunc(x[1]*10)
  if (p%2 + q%2)==0: #both even
    y_train[a] = 2.0
  if (p%2 + q%2)==2: #both odd
    y_train[a] = 1.0
  a += 1

a=0
for x in x_test:
  p = np.trunc(x[0]*10)
  q = np.trunc(x[1]*10)
  if (p%2 + q%2)==0: #es par ambos
    y_test[a] = 2.0
  if (p%2 + q%2)==2: #es impar ambos
    y_test[a] = 1.0
    
  a += 1


In [6]:
x_test[:5], y_test[:5]

(array([[0.48, 0.48],
        [0.51, 0.17],
        [0.84, 0.37],
        [0.52, 0.68],
        [0.69, 0.82]]),
 array([2., 1., 0., 0., 2.]))

In [7]:
#set the model and train it
svc = svm.SVC(gamma=0.00001,C=100, kernel='rbf')
svc.fit(x_train,y_train)

SVC(C=100, gamma=1e-05)

In [8]:
svc.score(x_test,y_test)

0.4866666666666667

### Random Forest

In [9]:
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier(n_estimators=100)

In [10]:
rfc.fit(x_train,y_train)

RandomForestClassifier()

In [11]:
rfc.score(x_test,y_test)

0.97

In [12]:
x_test[:15], rfc.predict(x_test[:15])

(array([[0.48, 0.48],
        [0.51, 0.17],
        [0.84, 0.37],
        [0.52, 0.68],
        [0.69, 0.82],
        [0.33, 0.64],
        [0.72, 0.59],
        [0.24, 0.93],
        [0.46, 0.54],
        [0.89, 0.18],
        [0.34, 0.55],
        [0.48, 0.56],
        [0.  , 0.95],
        [0.16, 0.76],
        [0.63, 0.04]]),
 array([0., 1., 0., 0., 2., 0., 1., 0., 0., 0., 1., 0., 0., 1., 2.]))

If you see the score, the right option is Random Forest for this problem. 

Sometimes you hesitate about wich algorithm is the right choice, but you can try both. AI does the math, solves the problem for us. 